development:
  server: "http://18.85.55.5:9292/faye"
  secret_token: "secret"
test:
  server: "http://18.85.55.5:9292/faye"
  secret_token: "secret"
production:
  server: "http://example.com/faye"
  secret_token: "3986a6637cfdcd24fcb9367f129c746a7546f7d80a04e4f74407374b1f58daad"
  signature_expiration: 3600 # one hour
